require: rubocop-rails

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metric/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateName:
  Enabled: false