default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: db/nanoblog_development.sqlite3

test:
  <<: *default
  database: db/nanoblog_test.sqlite3

production:
  <<: *default
  adapter: postgresql
  socket: /tmp/postgresql.sock
  database: <%= ENV.fetch('NANO_DB_NAME') %>
  username: <%= ENV.fetch('NANO_DB_USER') %>
  password: <%= ENV.fetch('NANO_DB_PASS') %>
  host: <%= ENV.fetch('NANO_DB_HOST') %>
